# Generated by Django 2.2.6 on 2019-10-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'managed': True, 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AddField(
            model_name='users',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='prenoms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
