# Generated by Django 2.2.6 on 2019-10-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appevent', '0003_auto_20191010_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateurs',
            options={'managed': True, 'verbose_name': 'Utilisateurs', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.CreateModel(
            name='Image_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('date_udapte', models.DateField()),
                ('dat_add', models.DateField()),
                ('statut', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appevent.Events')),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
