# Generated by Django 2.2.6 on 2019-10-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appevent', '0004_auto_20191010_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_event',
            options={'managed': True, 'verbose_name': 'Image_event', 'verbose_name_plural': 'Image_events'},
        ),
    ]
