# Generated by Django 2.2.6 on 2019-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevent', '0005_auto_20191010_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='nom_event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
